#!/bin/bash

if [ $# -eq 0 ];
then

		command='build'
else

		command=$1
fi

make

P_NAME="nxs-fw-ctl"
VER=`./objs/nxs-fw-ctl -V`

function build_package()
{

	clean_build_files

	(
		dh_make -p ${P_NAME}_${VER} --email b.ershov@nixys.ru --single --templates `pwd`/build-pkgs-tpls/debian --yes --createorig

		dpkg-buildpackage

		rm -rf ./debian
  )
}

function clean_build_files()
{

	rm ../${P_NAME}_${VER}-1_amd64.changes ../${P_NAME}_${VER}-1_amd64.deb ../${P_NAME}_${VER}-1.debian.tar.xz ../${P_NAME}_${VER}-1.dsc ../${P_NAME}_${VER}.orig.tar.xz
}

case $command in

	build)

		build_package
		;;

	clean)

		clean_build_files
		;;

	*)

		echo "Unknown command: $command"
		;;
esac
