#ifndef _INCLUDE_NXS_FW_CTL_U_PROJECTS_VERSION_TYPEDEF_H
#define _INCLUDE_NXS_FW_CTL_U_PROJECTS_VERSION_TYPEDEF_H

// clang-format off



#endif /* _INCLUDE_NXS_FW_CTL_U_PROJECTS_VERSION_TYPEDEF_H */
