FROM centos:6

ADD packages.nixys.ru.repo /etc/yum.repos.d/packages.nixys.ru.repo
RUN rpm --import http://packages.nixys.ru/packages.nixys.ru.gpg.key && \
	yum install -y epel-release && \
	yum install -y nxs-fw-libs-%%NXS_TPL_FW_VERSION%% redhat-lsb
RUN rpmdev-setuptree
