#ifndef _INCLUDE_NXS_FW_CTL_U_PROJECTS_CORE_MODULES_SUBUNITS_H
#define _INCLUDE_NXS_FW_CTL_U_PROJECTS_CORE_MODULES_SUBUNITS_H

// clang-format off

/*%%_NXS_TPL_HEADERS_TYPEDEF_BEGIN_%%*/
/*%%_NXS_TPL_HEADERS_TYPEDEF_END_%%*/

/*%%_NXS_TPL_HEADERS_BEGIN_%%*/
/*%%_NXS_TPL_HEADERS_END_%%*/

#endif /* _INCLUDE_NXS_FW_CTL_U_PROJECTS_CORE_MODULES_SUBUNITS_H */
