FROM debian:9

RUN apt-get update; apt-get install -y gnupg && \
	apt-key adv --fetch-keys http://packages.nixys.ru/debian/repository.gpg.key && \
	echo "deb [arch=amd64] http://packages.nixys.ru/debian/ stretch main" > /etc/apt/sources.list.d/packages.nixys.ru.list && \
	apt-get update; apt-get install -y nxs-fw-libs-%%NXS_TPL_FW_VERSION%%

COPY docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
